source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'  

use_frameworks!

target 'Weather02' do  
  
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftyJSON'
  
end
